variables:
  SCHEDULER_PARAMETERS: '--nodes=1 --partition=power9-eap-ci --export=NONE'
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - performance-target
  - performance-regression

.gcc-mpi-cuda-performance-regression:
  variables: 
    CMAKE_CXX_COMPILER: $CI_PROJECT_DIR/external/Kokkos/bin/nvcc_wrapper
  script:
    - env
    - printf 'env -i bash --norc --noprofile %s/scripts/darwin/build_fast_target.sh  "%s" "%s" "%s" "%s"\n' ${CI_PROJECT_DIR} ${GITHUB_APP_PEM} ${CI_COMMIT_SHA} ${CI_COMMIT_BRANCH} ${CI_JOB_URL}> execute_main.sh
    - printf 'env -i bash --norc --noprofile %s/scripts/darwin/metrics.sh "%s" "%s/build" "%s" "%s"\n' ${CI_PROJECT_DIR} ${GITHUB_APP_PEM} ${CI_PROJECT_DIR} ${CI_COMMIT_SHA} ${CI_COMMIT_BRANCH}>> execute_main.sh
    - env -i bash --norc --noprofile ${CI_PROJECT_DIR}/scripts/darwin/build_fast.sh "${GITHUB_APP_PEM}" "${CI_COMMIT_SHA}" "${CI_COMMIT_BRANCH}" "${CI_JOB_URL}"
    - env -i bash --norc --noprofile ${CI_PROJECT_DIR}/scripts/darwin/metrics.sh "${GITHUB_APP_PEM}" "${CI_PROJECT_DIR}/build" "${CI_COMMIT_SHA}" "${CI_COMMIT_BRANCH}"

.gcc-mpi-cuda-performance-regression-target-branch:
  script:
    - printf 'env -i bash --norc --noprofile %s/scripts/darwin/build_fast_target.sh  "%s" "%s" "%s" "%s"\n' ${CI_PROJECT_DIR} ${GITHUB_APP_PEM} ${CI_COMMIT_SHA} ${CI_COMMIT_BRANCH} ${CI_JOB_URL}> execute_target.sh
    - |
      PASS_OR_FAIL=$(env -i bash --norc --noprofile ${CI_PROJECT_DIR}/scripts/darwin/build_fast_target.sh "${GITHUB_APP_PEM}"  "${CI_COMMIT_SHA}" "${CI_COMMIT_BRANCH}" "${CI_JOB_URL}")
      echo "PASS_OR_FAIL ${PASS_OR_FAIL}"
      exit ${PASS_OR_FAIL}

parthenon-power9-gcc-mpi-cuda-perf-manual-target-branch:
  extends: .gcc-mpi-cuda-performance-regression-target-branch
  stage: performance-target
  allow_failure: false
  when: manual
  except:
    - schedules

parthenon-power9-gcc-mpi-cuda-perf-manual:
  extends: .gcc-mpi-cuda-performance-regression
  stage: performance-regression
  needs: [parthenon-power9-gcc-mpi-cuda-perf-manual-target-branch]
  except:
    - schedules

parthenon-power9-gcc-mpi-cuda-perf-schedule:
  extends: .gcc-mpi-cuda-performance-regression
  stage: performance-regression
  only:
    - schedules
    - develop

